name: cs6242-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pip
  - pip:
    - pandas>2,<2.1
    - scikit-learn==1.2.2
    - matplotlib
    - seaborn
    - streamlit
    - watchdog
    - pygwalker